In [1]:
import pandas as pd

In [2]:
! pip install mysql-connector-python sqlalchemy
! pip install "pymongo[srv]"

Requirement already satisfied: mysql-connector-python in /home/marshall/anaconda3/lib/python3.10/site-packages (8.0.33)
Requirement already satisfied: sqlalchemy in /home/marshall/anaconda3/lib/python3.10/site-packages (1.4.39)
Requirement already satisfied: protobuf<=3.20.3,>=3.11.0 in /home/marshall/anaconda3/lib/python3.10/site-packages (from mysql-connector-python) (3.20.3)
Requirement already satisfied: greenlet!=0.4.17 in /home/marshall/anaconda3/lib/python3.10/site-packages (from sqlalchemy) (2.0.1)
Requirement already satisfied: pymongo[srv] in /home/marshall/anaconda3/lib/python3.10/site-packages (4.4.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /home/marshall/anaconda3/lib/python3.10/site-packages (from pymongo[srv]) (2.3.0)

In [3]:
from sqlalchemy import create_engine
import pymongo

#### Conexión base de datos no relacional

In [4]:
usuario='fesalu'
passwd='nosqlfes123'
cluster='cluster0-shard-00-00.8pyt4.mongodb.net'
n1='cluster0-shard-00-01.8pyt4.mongodb.net'
n2='cluster0-shard-00-02.8pyt4.mongodb.net'
puerto='27017'
mongo_str=f"mongodb://{usuario}:{passwd}@{cluster}:{puerto},{n1}:{puerto},{n2}:{puerto}/?ssl=true&replicaSet=atlas-nok9e6-shard-0&authSource=admin&retryWrites=true&w=majority"
print(mongo_str)
mongoClient=pymongo.MongoClient(mongo_str)
mongoClient

mongodb://fesalu:nosqlfes123@cluster0-shard-00-00.8pyt4.mongodb.net:27017,cluster0-shard-00-01.8pyt4.mongodb.net:27017,cluster0-shard-00-02.8pyt4.mongodb.net:27017/?ssl=true&replicaSet=atlas-nok9e6-shard-0&authSource=admin&retryWrites=true&w=majority

MongoClient(host=['cluster0-shard-00-02.8pyt4.mongodb.net:27017', 'cluster0-shard-00-00.8pyt4.mongodb.net:27017', 'cluster0-shard-00-01.8pyt4.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='atlas-nok9e6-shard-0', authsource='admin', retrywrites=True, w='majority', tls=True)

In [5]:
#Generar un DF con una o varias tablas de una URL diferente a las vistas en la sesión
url='https://es.wikipedia.org/wiki/Los_Angeles_Rams'
df_html3=pd.read_html(url)
print(type(df_html3))
print("Numero de tablas en DF: ",len(df_html3))
df_html3[1]

<class 'list'>
Numero de tablas en DF:  3

,0,1,2,3,4
0,Números retirados por Los Angeles Rams,Números retirados por Los Angeles Rams,Números retirados por Los Angeles Rams,Números retirados por Los Angeles Rams,Números retirados por Los Angeles Rams
1,N.º,Jugador,Puesto,Periodo,Fecha
2,7,Bob Waterfield,QB,1945-1952,1952
3,28,Marshall Faulk,RB,1999-2005,21 de diciembre de 2007
4,29,Eric Dickerson,RB,1983-1987,NaN
5,74,Merlin Olsen,DE,1962-1976,NaN
6,75,Deacon Jones,DE,1961-1971,27 de septiembre de 2009
7,78,Jackie Slater,OT,1976-1995,1996
8,80,Isaac Bruce,WR,1994-2007,31 de octubre de 2010
9,85,Jack Youngblood,DE,1971-1984,1996

### Conexión base de datos relacional

In [6]:
us='fesalu'
passwd='bdfes2023'
url='bd.arcelia.net'
puerto='3306'
bd='bdcolegio02'
auth='mysql_native_password'

str_conn='mysql+mysqlconnector://{0}:{1}@{2}:{3}/{4}?auth_plugin={5}'
str_conn=str_conn.format(us,passwd,url,puerto,bd,auth)
str_conn
conn = create_engine(str_conn)
conn

Engine(mysql+mysqlconnector://fesalu:***@bd.arcelia.net:3306/bdcolegio02?auth_plugin=mysql_native_password)

In [7]:
#Generar un DF de alumnos o alumnas de la tabla alumnos de la base bdcolegio02 del servidor bd.arcelia.net
sql = '''SELECT * FROM alumnos WHERE sexo = %s'''
# SELECT * FROM Alumnos WHERE genero = 'F'
df_mysql2 = pd.read_sql_query(sql=sql, con=conn, params=['F'])
df_mysql2

,clave_alu,clave_admin,ap_paterno,ap_materno,nombre,sexo,curp,peso,estatura,direccion,colonia,cp,ciudad,id_estado,delegacion,telefono,celular,email,status_alu,fedita
0,11030172,4812,BORBOLLA,RAMOS,ARGELIA,F,,52.0,1.60,CLUB CAMPESTRE #867,CLUB CAMPESTRE,26190,QUERETARO,22,QUERETARO,4455497989,9612497989,argi_gogos@miemail.com,AC,2021-11-21 20:08:41
1,11030173,4849,CASTRO,MANCERA,KARLA MARIANA,F,,0.0,0.00,LAGO DE XOCHIMILCO 666,LOMAS DE SAN PABLO,26130,SANTIAGO DE QUERETARO,22,QUERETARO,,,,AC,2021-11-07 22:02:27
2,11030207,4808,AGUILAR,ZAMARRIPA,MICHELLE IVONNE,F,AUZM910928MQTGMC08,47.5,1.71,ECOLOGIA 689,TECNOLOGICO,26158,QUERETARO,22,QUERETARO,,,,AC,2021-10-04 20:53:54
3,11030218,4717,FLORES,NAMUR,MARIA FERNANDA,F,FONF910110MQTLMR00,58.0,1.62,BOTANICA#609,TECNOLOGICO,26158,QUERETARO,22,QUERETARO,4458585556,9618285226,maferfn@miemail.com,AC,2021-09-17 20:30:41
4,11030254,4724,GONZALEZ,DIAZ,CLAUDIA ALEJANDRA,F,GODC910202MDFNZL01,60.0,1.63,FRAY ANTONIO MARGIL DE JESUS #96,LOS MOLINOS 2DA. SECCION,26150,SANTIAGO DE QUERETARO,22,EPIGMENIO GONZALEZ,0444458170558,0449618170258,jlgg1504@telmart.com.mx,AC,2021-09-04 19:40:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,11080201,,SOTO,ELIAS,PALOMA DENISSE,F,SOEP921030MQTTLL03,52.0,1.51,70 DE NOVIEMBRE NO. 7 PTE.,CENTRO SANTA ROSA JAUREGUI,26220,QUERETARO,22,SANTA ROSA JAUREGUI QRO,0444458775868,0449618772868,chiquis_palomit@miemail.com,AS,2023-03-12 16:41:30
279,11080202,,VALLES,RAMOS,MARIANA,F,VARM930602MCHLMR08,62.0,1.66,MARIO GONZALEZ #0,FRACCIONAMIENTO VILLA CORZO,32980,SAN JOSE ITURBIDE,12,SAN JOSE ITURBIDE,4191089618,4191089618,mariana_020693@miemail.com,AS,2023-03-10 14:00:21
280,11080205,,BADUY,VALDEZ,KENNIA ASENET,F,BAKV931111MQTDLN18,59.0,1.60,FRAY FRANCISCO DE LOS ANGELES #766,QUINTAS DEL MARQUEZ,26042,QUERETARO,22,QUERETARO,4451544548,9611244548,keny_625@miemail.com,AS,2023-03-12 19:45:44
281,11080208,,BECERRIL,HUERTA,MARIANA,F,BEHM930222MQTCRR06,52.0,1.59,PASEO DE SOFIA # 709,TEJEDA,26904,QUERETARO,22,CORREGIDORA,4458448574,9618448574,mane_chiquis@miemail.com,AS,2023-03-11 19:46:25
282,11080209,NULL,MORALES,CARMONA,KARLA MARIANA,F,,NaN,NaN,None,None,None,None,18,None,None,None,None,AS,2023-04-15 20:48:37

In [8]:
sql = '''SELECT * FROM alumnos WHERE sexo = %s'''
# SELECT * FROM Alumnos WHERE genero = 'M'
df_mysql2 = pd.read_sql_query(sql=sql, con=conn, params=['M'])
df_mysql2

,clave_alu,clave_admin,ap_paterno,ap_materno,nombre,sexo,curp,peso,estatura,direccion,colonia,cp,ciudad,id_estado,delegacion,telefono,celular,email,status_alu,fedita
0,11030177,4716,FERRUSCA,ANDRADE,OCTAVIO,M,,62.0,1.68,MARQUES DE BARCELO #608,LOMAS DEL MARUQES,26146,QUERETARO,22,QUERETARO,4458114845,9618114845,tavoferrus_11@miemail.com,AC,2021-10-15 16:23:00
1,11030178,4720,GARCIA,GOMEZ,RAFAEL,M,220140190055288,55.0,1.82,PAJAROS # 687,CALESA SEGUNDA SECCION,26020,QUERETARO,22,QUERETARO,4451986967,9611986967,arobertogarcia@telmart.net.mx,AC,2021-10-25 09:22:33
2,11030180,5380,GUTIERREZ,FLORES,CARLOS DAVID,M,GUFC910124HDFTLR04,60.0,1.75,CIRCUITO SAN IGNACIO 670 INT 6,FRACCIONAMIENTO SANTIAGO,26129,QUERETARO,22,SANTIAGO DE QUERETARO,4455558865,9612558865,chorok_skp91@miemail.com,AC,2021-09-27 21:52:05
3,11030188,4857,MARTINEZ,RIVERA,JAVIER JOSUE,M,MARJ910422HQTRVV01,52.0,1.66,ASUNCION NO. 698,EL ROSARIO,26128,QUERETRO,22,QUERETARO,0444458817907,0449618817907,c_h_a_p_a_r_r_o-pi_cha_ka@miemail.com,AC,2022-10-11 20:23:14
4,11030199,4769,ROSALES,APREZA,NESTOR MARTIN,M,,53.0,1.63,RIO BALSAS #707,LOS ARQUITOS,26050,QUERETARO,22,QUERETARO SUR,0444458591085,0449618291082,nestoriwh@hotmai.com,AC,2021-09-22 17:57:13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,11080203,,VILLAGRANA,BARRAGAN,CARLOS IVAN,M,VIBC911114HDFLRR06,61.0,1.72,MARQUES DE LAS AMARILLAS NO. 687,LOMAS DEL MARQUES,26146,QUERETARO,22,SANTIAGO DE QUERETARO,4458517765,9618517765,chino-vergoza@miemail.com,AS,2023-03-08 16:53:59
395,11080204,,AGUILLON,RESENDIZ,JOSE,M,AURJ941216HQTGSS06,57.0,160.00,EULOGIO MARROQUIN 707,CANDILES,26190,QUERETARO,22,CORREGIDORA,4458170450,9618170420,blackjarrior_9412@miemail.com,AS,2023-03-10 11:05:13
396,11080206,,NAVA,TORRES,LEONARDO JESUS,M,NATL9408HDFVRN05,0.0,0.00,PASEO DE MOSCU #868,TEJEDA,26190,QUERETARO,22,SANTIAGO DE QUERETARO,4458770708,9618770708,leo94-88@infinitum.com.mx,AS,2023-03-11 19:56:28
397,11080207,,LOPEZ,AGUILAR,DANIEL,M,LOAD940404HBCPGN06,0.0,0.00,HDA DE LOS MORALES # 707,RINCON DE LOS ARCOS,36636,IRPUATO,12,IRAPUATO,4651551906,4621251906,marydm72@miemail.com,AS,2023-03-07 11:17:06
398,11080210,,GUERRERO,COLOMBRES,ALDO ENRICO,M,GUCA960125HDFRLL09,44.0,1.59,AVENIDA PE,SAN PEDRITO PE,,SANTIAGO DE QUERETARO,22,,5585511084,5582211084,colombresm@att.com.mx,AS,2023-04-15 20:48:37